[project]
  authors         = [{ name = "kodiitulip", email = "kodii.tulip@gmail.com" }]
  description     = "Uma aplicação para geração de dungeons"
  name            = "darkest-gen"
  readme          = "README.md"
  requires-python = ">=3.12"
  version         = "0.1.0"
